"""empty message

Revision ID: 5ffdd75eb242
Revises: 905abe8d88e5
Create Date: 2022-02-04 14:34:58.578655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffdd75eb242'
down_revision = '905abe8d88e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verifying_status', sa.Boolean(), nullable=False))
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'verifying_status')
    # ### end Alembic commands ###
