"""empty message

Revision ID: 905abe8d88e5
Revises: 70dee96fdc03
Create Date: 2022-02-02 21:12:30.998628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905abe8d88e5'
down_revision = '70dee96fdc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission_status')
    # ### end Alembic commands ###
