"""add new column

Revision ID: b7d0a7c033ce
Revises: edf56ca5c621
Create Date: 2022-02-04 14:48:34.188064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d0a7c033ce'
down_revision = 'edf56ca5c621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('verifying_status',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verifying_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
