"""empty message

Revision ID: ca914a6d2c02
Revises: 5ffdd75eb242
Create Date: 2022-02-04 14:42:21.221710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca914a6d2c02'
down_revision = '5ffdd75eb242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verifying_status', sa.String(), nullable=True))
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'verifying_status')
    # ### end Alembic commands ###
