"""add new column

Revision ID: d626ec0de113
Revises: b7d0a7c033ce
Create Date: 2022-02-04 14:53:02.655700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd626ec0de113'
down_revision = 'b7d0a7c033ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    op.add_column('users', sa.Column('verifying_status', sa.Boolean(), nullable=False))
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'verifying_status')
    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(), nullable=False),
    sa.Column('user_telegram_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_status', sa.BOOLEAN(), nullable=False),
    sa.Column('verifying_status', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
