"""empty message

Revision ID: edf56ca5c621
Revises: ca914a6d2c02
Create Date: 2022-02-04 14:43:08.695484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf56ca5c621'
down_revision = 'ca914a6d2c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'verifying_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verifying_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
